### ISSUE TITLE
'DeadEnd' bug

### ISSUE THREAD

**Issue by blogle** [SEL-Columbia/NetworkBuild#14]
Discovered a bug yesterday that explains #12 (whether that distance calculation should be changed is not clear) and in solving will implement #13. Ultimately, if a two way mv test fails that components queue 'blocks' until sufficient MV is aggregated on the foreign component to make the connection. But if that never happens, the edge is still blocking any advancement on that queue and therefore no state changes occur in that iteration and the algorithm terminates prematurely.

After an extensive whiteboard session with Natali, we think we can implement a structure that tracks the neighborhood around these dead end components and prunes them from the search space thus eliminating the problem. The state change criteria, needs extended however such that it comprises both Et and dead_ends. If neither change then the outer loop can terminate.

**Comment by chrisnatali** [comment]
Example graph with mvMax values illustrating the problem:

a-----b
|    /
| /
c

node | mvMax  
--------|----------
a        | 2           
b        | 6
c        | 6

edge | weight
--------|-----------
(a,b)  | 4
(a,c)  | 4
(b,c)  | 5

Here, node a is node c's nearest neighbor.  However, since node a does not have sufficient mvMax to connect to any other node, node c will never connect to it.  Node c DOES have sufficient mvMax to connect to node b (and vice-versa), but without "pruning" node a from the search space, it will never connect.  

Detecting and tracking DeadEnd nodes/components and eliminating them from the search space *should* resolve this.  It makes the algorithm less generic, but It may be worth doing a pass over all valid components before https://github.com/SEL-Columbia/NetworkBuild/blob/master/networkbuild/ModBoruvka.py#L57 to check for those whose mvMax is less than the distance to it's nearest neighbor and prune them from the component set.
